spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  shardingsphere:
    mode:
      overwrite: true
      type: Standalone
      repository:
        type: File
        props:
          path: sharding-config
    # 配置库
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ds0
        username: test
        password: test
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ds1
        username: test
        password: test
    rules:
      sharding:
        # 分片算法
        sharding-algorithms:
          # 库
          database-sharding:
            type: INLINE
            props:
              algorithm-expression: ds$->{f_id % 2}
          # 表
          table-sharding:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.learning.sharding.TableSharingAlgorithm
        keyGenerators:
          snow-flake:
            type: SNOWFLAKE
            props:
              worker-id: 123
        tables:
          # 表规则
          t_order:
            actual-data-nodes: ds$->{0..1}.t_order_$->{202201..202204}
            database-strategy:
              standard:
                sharding-column: f_id
                sharding-algorithm-name: database-sharding
            table-strategy:
              standard:
                sharding-column: f_month
                sharding-algorithm-name: table-sharding
            key-generate-strategy:
              column: f_id
              key-generator-name: snow-flake
    props:
      sql-show: true
  level:
    com:
      light:
        sharding:
          jdbc: debug
